POST http://localhost:4000/posts HTTP/2.0
content-type: application/json

{
    "title":"Hello world!"
}

###

GET http://localhost:4000/posts

###

POST http://localhost:4001/posts/a90c9eab/comments
Content-Type: application/json

{
    "content":"beautiful"
}

###

GET http://localhost:4001/posts/a90c9eab/comments
